### ISSUE TITLE
AttributeError: type object 'ParseMode' has no attribute 'MARKDOWN_V2'

### ISSUE THREAD

**Issue by Helias** [TendTo/DMI-Insider-newsgen-bot#1]
![image](https://user-images.githubusercontent.com/519778/93720930-b6dab080-fb8c-11ea-8052-d073820196b4.png)

**Comment by TendTo** [comment]
Ok, it's a bit of a strange error, because 'ParseMode' is among the Telegram-bot modules, and it has the MARKDOWN_V2 attribute.
Furthermore, testing didn't prompt any errors, even when done through the github action, and that exact line runs often.
I tried updating the requirements with `python3 -m pip install -r requirements.txt`, and now it seems to work, so i assume this was the problem.
Anyway, this issue will remain open at least for some days, to be sure this solved it and that the error won't show itself again
